# Robust Wireless Sensing using Probabilistic and Statistical Assessments ：Artifact - Interactive Demo
<img src="./overview2.jpg" width="100%" style="float:left" />



## Step 1. Training the underlying model and use it to predict test samples.

## Step 2. Training an anomaly detector for each class according to the training samples.
## Step 3. Evaluate the ability of the underlying model to predict the test sample.
## Step 4. Performance of the RISE.

## Preliminaries
This interactive Jupyter notebook provides an example to show the performance of RISE. 
## Instructions for Experimental Workflow:
Select each cell in turn and use “Cell” > “Run Cell” from the menu to run specific cells. Note that some cells depend on previous cells being executed. If any errors occur, ensure all previous cells have been executed.
## Important Notes
#### Some cells can take a few minutes to complete; please wait for the results until step to the next cell.

## Step 1. Performance of the underlying model without RISE
Here we provide the results of each experimental environment for each case study.
You can change the scene names at two places in each piece of code to get results for different scenarios.


In [5]:
#Import different data sets

##-------------------------------Case study 1: Gesture recognition----------------------------------------##

#### For WiG, you can change S1  S2  S3  S4  S5
filepath_AR = '/root/RISE-Version2/Jupyter/WiG_test/S1/'
from WiG_test.S1.test_start import start
x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start()

# ### For WiAG, you can change S1  S2  S3  S4  S5
# filepath_AR = '/root/RISE-Version2/Jupyter/WiAG_test/S4/'
# from WiAG_test.S4.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start()

# #### For WiAG_C, you can change L1 L2  L3  L4  L5
# filepath_AR = '/root/RISE-Version2/Jupyter/WiAG_C_test/L5/'
# from WiAG_C_test.L5.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start()  

# #### For WiAG_O, you can change L1 L2  L3  L4  L5
# filepath_AR = '/root/RISE-Version2/Jupyter/WiAG_O_test/L4/'
# from WiAG_O_test.L4.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start() 

# #### For TACT, you can change S1 S2 S3 S4 S5 
# filepath_AR = '/root/RISE-Version2/Jupyter/TACT_test/S1/'
# from TACT_test.S1.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start()  

# #### For AllSee, you can change S1 S2 S3 S4 S5
# filepath_AR = '/root/RISE-Version2/Jupyter/AllSee_test/S5/'
# from AllSee_test.S5.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start() 

# #### For EI, you can change S1 S2 S3 S4 S5 
# filepath_AR = '/root/RISE-Version2/Jupyter/EI_test/S2/'
# from EI_test.S2.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start(filepath_AR) 

##-------------------------------Case study 2: Gait recognition----------------------------------------##

# #### For WiWho, you can change S1 S2 S3 S4 S5
# filepath_AR = '/root/RISE-Version2/Jupyter/WiWho_test/S5/'
# from WiWho_test.S5.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start() 

# #### For WifiU, you can change S1 S2 S3 S4 S5
# filepath_AR = '/root/RISE-Version2/Jupyter/WifiU_test/S5/'
# from WifiU_test.S4.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start()


##-------------------------------Case study 3: Activity recognition----------------------------------------##

# #### For VibWrite_R, you can change N _1 _2 _3 _4
# filepath_AR = '/root/RISE-Version2/Jupyter/VibWrite_R_test/_4/'
# from VibWrite_R_test._4.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start()

# #### For VibWrite_A, you can change N _1 _2 _3 _4
# filepath_AR = '/root/RISE-Version2/Jupyter/VibWrite_A_test/_4/'
# from VibWrite_A_test._4.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start()

# #### For Taprint_R, you can change S D M W 
# filepath_AR = '/root/RISE-Version2/Jupyter/Taprint_R_test/W/'
# from Taprint_R_test.W.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start()

# #### For Taprint_A, you can change S D M W 
# filepath_AR = '/root/RISE-Version2/Jupyter/Taprint_A_test/W/'
# from Taprint_A_test.W.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start()

# #### For UDO_Free, you can change RP LP DC DB 
# filepath_AR = '/root/RISE-Version2/Jupyter/UDO_Free/DB/'
# from UDO_Free.DB.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_    dif,class_num,class_index = start()

# #### For M_Touch, you can change S DP T M
# filepath_AR = '/root/RISE-Version2/Jupyter/M_Touch/M/'
# from M_Touch.M.test_start import start
# x_train1, y_train1, x_test1, y_test1, myclassifier, y_true_dif, y_pred_dif,class_num,class_index = start()



--------  The performance of the underlying model without RISE --------

The accuracy without RISE:  0.85
Confusion matrix without RISE: 
 [[30  0  0  0  0  0]
 [ 0 30  0  0  0  0]
 [ 6  0 24  0  0  0]
 [17  0  0 13  0  0]
 [ 0  0  0  0 30  0]
 [ 0  0  0  4  0 26]]


## Step 2. Training an Anomaly Detector for each class according to the training data.
For convenience, we have saved trained anomaly detectors for each experimental environment. However, you can also run the following cell to train the anomaly detector. 

In [2]:

for tt in range(class_num):
    print('clf_p_prob_'+ str(tt)+'\n')

# ############################ Trainning Anomaly Detector  ###############################  
# from sklearn.model_selection import StratifiedKFold
# import numpy as np
# from sklearn import preprocessing
# from nonconformist.nc import MarginErrFunc
# import warnings
# warnings.filterwarnings("ignore", message="Numerical issues were encountered ")
# import sys
# sys.path.insert(0,'/root/RISE-Version2/')
# from Statistical_vector.statistical_vector import train_statistical_vector, test_statistical_vector_param, non_condition_p
# import random
# from sklearn import svm
# import joblib
# import sklearn.ensemble
# from sklearn import neighbors
# from sklearn.linear_model import LogisticRegression
# from sklearn.ensemble import  AdaBoostClassifier
# from sklearn.ensemble import VotingClassifier

# ## Probability vector and statistical vector are calculated according to the training data
# skf = StratifiedKFold(n_splits=3, random_state=0,shuffle=True)
# cal_proba = np.empty(shape=[0, (class_num)*4])
# cal_score = np.empty(shape=[0, 1*4])
# train_proba = np.empty(shape=[0, (class_num)*4])
# train_nonconformity = np.empty(shape=[0, (class_num)*4])
# train_p = np.empty(shape=[0, (class_num)*4])
# cal_label = np.empty(shape=[0,1])
# train_label = np.empty(shape=[0,1])
# for train_index, cal_index in skf.split(x_train1, y_train1):
#     data_train = x_train1[train_index, :] 
#     label_train = y_train1[train_index]
#     data_cal = x_train1[cal_index, :]
#     label_cal = y_train1[cal_index]
    
#     train_p1_svm_, train_proba1_svm_ = train_statistical_vector(data_train, label_train, data_cal, label_cal, 
#                        classification_model = myclassifier[0], non_Func = MarginErrFunc(), significance=None) 
#     train_p1_rf_, train_proba1_rf_ = train_statistical_vector(data_train, label_train, data_cal, label_cal, 
#                        classification_model = myclassifier[1], non_Func = MarginErrFunc(), significance=None) 
#     train_p1_lr_, train_proba1_lr_ = train_statistical_vector(data_train, label_train, data_cal, label_cal, 
#                        classification_model = myclassifier[4], non_Func = MarginErrFunc(), significance=None)
#     train_p1_gbc_, train_proba1_gbc_ = train_statistical_vector(data_train, label_train, data_cal, label_cal, 
#                        classification_model = myclassifier[5], non_Func = MarginErrFunc(), significance=None)
    
#     train_proba1 = np.hstack((train_proba1_svm_, train_proba1_rf_, train_proba1_lr_, train_proba1_gbc_))
#     train_p1 = np.hstack((train_p1_svm_, train_p1_rf_, train_p1_lr_, train_p1_gbc_))
#     train_proba = np.append(train_proba, train_proba1, axis=0)  
#     train_p = np.append(train_p, train_p1, axis=0)  
#     train_label = np.append(train_label,y_train1[train_index]) 
    
# p_thr = 0.1
# rows_ = []  
# for row_ in range(train_p.shape[0]):
#     if (max(train_p[row_,0:0+class_num]) > p_thr) & (max(train_p[row_,class_num:class_num*1+class_num]) > p_thr) \
#         & (max(train_p[row_,class_num*2:class_num*2+class_num]) > p_thr) & (max(train_p[row_,class_num*3:class_num*3+class_num]) > p_thr) :               
#             rows_.append(row_)
        
# pro_n_p = np.hstack((train_proba, train_p))
# group_it = pro_n_p[rows_,:] 
# train_label1 = train_label[rows_] 

# group_it = preprocessing.scale(group_it)
   
# index = [t for t in range(group_it.shape[0])] 
# random.shuffle(index)
# group_it1 = group_it[index] 
# train_p_lable1 = train_label1[index]



# ####Training an anomaly detector for each class

# ##Generalize probability vectors and statistical vectors for each class
# names = locals()
# fe_p_prob = np.hstack((train_p_lable1.reshape(-1,1),group_it1))
# for tt in range(class_num):
#     names['fe_p_prob_%s'%tt] = fe_p_prob[fe_p_prob[:,0]==tt]
#     names['fe_p_prob_%s'%tt] = np.delete(names['fe_p_prob_%s'%tt], 0, 1)  

# print('\n---------------  Training one-class SVM model for each class -----------------\n')    
# ##training one-class SVM model for each class
# for tt in range(class_num):
#     names['./save_model/clf_p_prob_%s'%tt] = svm.OneClassSVM(nu=0.5,kernel="linear" )
#     names['./save_model/clf_p_prob_%s'%tt].fit(names['fe_p_prob_%s'%tt])
#     print('clf_p_prob_'+ str(tt)+'\n')
#     ##save one-class SVM model for each class
#     joblib.dump(names['./save_model/clf_p_prob_%s'%tt],'./save_model/clf_p_prob_%s'%tt+'.model')
    

# ##Ensemble Learning
# clf_dif1 = sklearn.ensemble.RandomForestClassifier(n_estimators=100,random_state=0)
# clf_dif2 = svm.SVC(probability = True, random_state=0)
# clf_dif3 = neighbors.KNeighborsClassifier(n_neighbors=10)
# clf_dif4 = LogisticRegression(random_state=0)
# clf_dif7 = AdaBoostClassifier(random_state=0)   
# clf_pit = VotingClassifier(estimators = [('rf',clf_dif1),('svm',clf_dif2),
# ('knn',clf_dif3),('lr',clf_dif4),('AdaBoost',clf_dif7)],voting='hard')      
# clf_pit.fit(group_it1,train_p_lable1)
# joblib.dump(clf_pit,'./save_model/clf_pit.model') 


clf_p_prob_0

clf_p_prob_1

clf_p_prob_2

clf_p_prob_3

clf_p_prob_4

clf_p_prob_5



## Step 3. Evaluate the ability of the underlying model to predict the test data.
For convenience, we have saved the approval or rejection of the predicted results of the test sample by the anomaly detector. Approval is denoted by 1, rejection is denoted by -1.  However, you can also run the following cell to get the result.

In [3]:
import numpy as np
accept_or_reject = np.load(filepath_AR + 'accept_or_reject.npy') 
print(accept_or_reject)


# #####Calculate the probability vector and statistical vector of the test set
           
# from sklearn.model_selection import StratifiedShuffleSplit
# calibration_portion = 0.5
# split = StratifiedShuffleSplit(n_splits=1,
#                    test_size=calibration_portion)
# for train, cal in split.split(x_train1,y_train1):
#     cal_scores1_svm = np.empty(cal.reshape(-1,1).shape,dtype=float)
#     cal_scores1_rf = np.empty(cal.reshape(-1,1).shape,dtype=float)
#     cal_scores1_lr = np.empty(cal.reshape(-1,1).shape,dtype=float)
#     cal_scores1_gbc = np.empty(cal.reshape(-1,1).shape,dtype=float)
#     test_svmnc1_score = np.empty(np.array([x_test1.shape[0],class_num]),dtype=float)
#     test_rfnc1_score = np.empty(np.array([x_test1.shape[0],class_num]),dtype=float)
#     test_lrnc1_score = np.empty(np.array([x_test1.shape[0],class_num]),dtype=float)
#     test_gbcnc1_score = np.empty(np.array([x_test1.shape[0],class_num]),dtype=float)
#     test_svm1_proba = np.empty(np.array([x_test1.shape[0],class_num]),dtype=float)
#     test_rf1_proba = np.empty(np.array([x_test1.shape[0],class_num]),dtype=float)
#     test_lr1_proba = np.empty(np.array([x_test1.shape[0],class_num]),dtype=float)
#     test_gbc1_proba = np.empty(np.array([x_test1.shape[0],class_num]),dtype=float)
#     for repeat in range(10):
#         train_sample = np.random.choice(train.size, train.size, replace=True)
#         data_train = x_train1[train_sample, :]
#         label_train = y_train1[train_sample]
#         data_cal = x_train1[cal, :]
#         label_cal = y_train1[cal]
#         data_test = x_test1

#         cal_scores_svm, test_svmnc_score, test_svm_proba = test_statistical_vector_param(data_train, label_train,  data_cal, label_cal, data_test,
#                  classification_model=myclassifier[0], non_Func = MarginErrFunc(), significance=None)
#         cal_scores1_svm = np.hstack((cal_scores1_svm,cal_scores_svm.reshape(-1,1)))
#         test_svmnc1_score = np.dstack((test_svmnc1_score,test_svmnc_score))
#         test_svm1_proba = np.dstack((test_svm1_proba,test_svm_proba))
  
#         cal_scores_rf, test_rfnc_score, test_rf_proba = test_statistical_vector_param(data_train, label_train,  data_cal, label_cal, data_test,
#                  classification_model=myclassifier[1], non_Func = MarginErrFunc(), significance=None)
#         cal_scores1_rf = np.hstack((cal_scores1_rf,cal_scores_rf.reshape(-1,1)))
#         test_rfnc1_score = np.dstack((test_rfnc1_score,test_rfnc_score))
#         test_rf1_proba = np.dstack((test_rf1_proba,test_rf_proba))
          
#         cal_scores_lr, test_lrnc_score, test_lr_proba = test_statistical_vector_param(data_train, label_train,  data_cal, label_cal, data_test,
#                  classification_model=myclassifier[4], non_Func = MarginErrFunc(), significance=None)
#         cal_scores1_lr = np.hstack((cal_scores1_lr,cal_scores_lr.reshape(-1,1)))
#         test_lrnc1_score = np.dstack((test_lrnc1_score,test_lrnc_score))
#         test_lr1_proba = np.dstack((test_lr1_proba,test_lr_proba))
        
#         cal_scores_gbc, test_gbcnc_score, test_gbc_proba = test_statistical_vector_param(data_train, label_train,  data_cal, label_cal, data_test,
#                  classification_model=myclassifier[5], non_Func = MarginErrFunc(), significance=None)
#         cal_scores1_gbc = np.hstack((cal_scores1_gbc,cal_scores_gbc.reshape(-1,1)))
#         test_gbcnc1_score = np.dstack((test_gbcnc1_score,test_gbcnc_score))
#         test_gbc1_proba = np.dstack((test_gbc1_proba,test_gbc_proba))
        
        
#     ##Nonconformity score of the validation set of the test set    
#     cal_scores2_svm = np.mean(np.delete(cal_scores1_svm,0,1), axis=1)
#     cal_scores2_rf = np.mean(np.delete(cal_scores1_rf,0,1), axis=1)
#     cal_scores2_lr = np.mean(np.delete(cal_scores1_lr,0,1), axis=1)
#     cal_scores2_gbc = np.mean(np.delete(cal_scores1_gbc,0,1), axis=1) 
    
#     ##Nonconformity score of the test set
#     test_svmnc2_score = np.mean(np.delete(test_svmnc1_score,0,2), axis=2)
#     test_rfnc2_score = np.mean(np.delete(test_rfnc1_score,0,2), axis=2)
#     test_lrnc2_score = np.mean(np.delete(test_lrnc1_score,0,2), axis=2)
#     test_gbcnc2_score = np.mean(np.delete(test_gbcnc1_score,0,2), axis=2)
    
#     ##The probability vector of the test set
#     test_proba_svm_ = np.mean(np.delete(test_svm1_proba,0,2), axis=2)
#     test_proba_rf_ = np.mean(np.delete(test_rf1_proba,0,2), axis=2)
#     test_proba_lr_ = np.mean(np.delete(test_lr1_proba,0,2), axis=2)
#     test_proba_gbc_ = np.mean(np.delete(test_gbc1_proba,0,2), axis=2)

# ##The statistical vector of the test set    
# test_p_svm_ = non_condition_p(cal_scores2_svm, test_svmnc2_score)
# test_p_rf_ = non_condition_p(cal_scores2_rf, test_rfnc2_score)
# test_p_lr_ = non_condition_p(cal_scores2_lr, test_lrnc2_score)   
# test_p_gbc_ = non_condition_p(cal_scores2_gbc, test_gbcnc2_score)    
# test_group_it = np.hstack((test_proba_svm_, test_proba_rf_, test_proba_lr_, test_proba_gbc_, 
#                            test_p_svm_, test_p_rf_, test_p_lr_, test_p_gbc_))
# test_group_it = preprocessing.scale(test_group_it) 


# ##Determine whether the prediction of the original model is correct
# discarded_sample = [] 
# accept_sample = [] 
# discarded_right_sample = [] 
# accept_right_sample = [] 
# accept_or_reject = []   
# dis_test = np.empty((test_group_it.shape[0],class_num),float)
# for aa in range(class_num):
#     aa_prob = joblib.load('./save_model/clf_p_prob_%s'%aa+'.model')
#     dis_test[:,aa] = aa_prob.decision_function(test_group_it).flatten()            
# for t in range(len(y_pred_dif)):
#         result_it_d = np.argmax(dis_test[t,:])
#         svmit = joblib.load('./save_model/clf_pit.model')
#         result_it = svmit.predict(test_group_it[t].reshape(1,-1))
#         if (y_pred_dif[t] == result_it == result_it_d):
#             accept_sample.append(t)
#             accept_or_reject.append(1)
#             if(y_pred_dif[t] == y_true_dif[t]):
#                 accept_right_sample.append(t)
#         else:
#             discarded_sample.append(t)
#             accept_or_reject.append(-1)
#             if(y_pred_dif[t] == y_true_dif[t]):
#                 discarded_right_sample.append(t)   
                
# print('\n---------------  Evaluate the ability of the underlying model to predict the test data -----------------\n') 
# print(accept_or_reject)

[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1  1 -1  1  1  1
 -1  1  1 -1  1 -1 -1  1 -1 -1 -1 -1  1  1 -1  1  1 -1 -1 -1 -1  1 -1 -1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1 -1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1]


## Step 4. The performance of the RISE.
Accuracy: The ratio of the number of correctly predicted samples to the total number of testing samples.  
Precision：Of all detected drifting samples, how many are correct?  
Recall：Of all drifting samples, how many are actually detected by Rise?  
F1-score：A high F1-score means Rise can detect most drifting samples while rarely mis-classifying normal samples.


In [4]:
discarded_sample = np.load(filepath_AR + 'discarded_sample.npy')
discarded_right_sample = np.load(filepath_AR + 'discarded_right_sample.npy')
accept_sample = np.load(filepath_AR + 'accept_sample.npy')
accept_right_sample = np.load(filepath_AR + 'accept_right_sample.npy')

reject_num = len(discarded_sample) 
reject_num_right =  len(discarded_right_sample) 
accept_num = len(accept_sample) 
accept_num_right = len(accept_right_sample) 

TP = reject_num - reject_num_right
FP = reject_num_right
FN = accept_num - accept_num_right
TN = accept_num_right

Accuracy = (TP+TN)/(TP+FP+FN+TN)
Precision = TP/(TP+FP)
Recall = TP/(TP+FN)
F1_Score = 2 * Precision * Recall / (Precision + Recall)

print('\n ------------------ The performance of the RISE --------------------\n')
print('True Positive:',TP)
print('False Positive:',FP)
print('False Negative:',FN)
print('True Negative:', TN)
print('Accuracy:',Accuracy)
print('Precision:',Precision)
print('Recall:',Recall)
print('F1_Score:', F1_Score)



 ------------------ The performance of the RISE --------------------

True Positive: 24
False Positive: 0
False Negative: 3
True Negative: 153
Accuracy: 0.9833333333333333
Precision: 1.0
Recall: 0.8888888888888888
F1_Score: 0.9411764705882353
